### ISSUE TITLE
What is "stop"? 

### ISSUE THREAD

**Issue by Dipeshtamboli** [val-iisc/AAA#1]
https://github.com/val-iisc/AAA/blob/58c8ace830e3c79d7c735e188cfa40698bbf60fa/pd_b1.py#L164

It is giving me this error:
Traceback (most recent call last):
  File "/content/gdrive/My Drive/google_colab/AAA/pd_b1.py", line 164, in <module>
    stop
NameError: name 'stop' is not defined

How to fix it?

**Comment by ghost** [comment]
I just simply comment it out

**Comment by Dipeshtamboli** [comment]
Yes, commenting it solves the issue.
